development:
 adapter: mysql2
 encoding: utf8
 database: user_ebo
 username: root
 password: root

test:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: ebo_test
 pool: 5
 username: root
 password: root

production:
 adapter: postgresql
 encoding: unicode
 host: localhost
 pool: 5
 database: user_ebo
 username: root
 password: password
